/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRepayRouteImport } from './routes/app.repay'
import { Route as AppPrivacyRouteImport } from './routes/app.privacy'
import { Route as AppLiquidationRouteImport } from './routes/app.liquidation'
import { Route as AppDepositRouteImport } from './routes/app.deposit'
import { Route as AppBorrowRouteImport } from './routes/app.borrow'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRepayRoute = AppRepayRouteImport.update({
  id: '/repay',
  path: '/repay',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppLiquidationRoute = AppLiquidationRouteImport.update({
  id: '/liquidation',
  path: '/liquidation',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppBorrowRoute = AppBorrowRouteImport.update({
  id: '/borrow',
  path: '/borrow',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/borrow': typeof AppBorrowRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/liquidation': typeof AppLiquidationRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/repay': typeof AppRepayRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/borrow': typeof AppBorrowRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/liquidation': typeof AppLiquidationRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/repay': typeof AppRepayRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/borrow': typeof AppBorrowRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/liquidation': typeof AppLiquidationRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/repay': typeof AppRepayRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/borrow'
    | '/app/deposit'
    | '/app/liquidation'
    | '/app/privacy'
    | '/app/repay'
    | '/app/settings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/borrow'
    | '/app/deposit'
    | '/app/liquidation'
    | '/app/privacy'
    | '/app/repay'
    | '/app/settings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/borrow'
    | '/app/deposit'
    | '/app/liquidation'
    | '/app/privacy'
    | '/app/repay'
    | '/app/settings'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/repay': {
      id: '/app/repay'
      path: '/repay'
      fullPath: '/app/repay'
      preLoaderRoute: typeof AppRepayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/privacy': {
      id: '/app/privacy'
      path: '/privacy'
      fullPath: '/app/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/liquidation': {
      id: '/app/liquidation'
      path: '/liquidation'
      fullPath: '/app/liquidation'
      preLoaderRoute: typeof AppLiquidationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/borrow': {
      id: '/app/borrow'
      path: '/borrow'
      fullPath: '/app/borrow'
      preLoaderRoute: typeof AppBorrowRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBorrowRoute: typeof AppBorrowRoute
  AppDepositRoute: typeof AppDepositRoute
  AppLiquidationRoute: typeof AppLiquidationRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppRepayRoute: typeof AppRepayRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBorrowRoute: AppBorrowRoute,
  AppDepositRoute: AppDepositRoute,
  AppLiquidationRoute: AppLiquidationRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppRepayRoute: AppRepayRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
